/* Photo Config — Generated by JBR Admin */

var homepageConfig = {
    heroImage:   'images/hero.jpg',
    aboutImage:  'images/about.jpg',
    portfolioCarouselFolders: [
        'images/portraits',
        'images/sports',
        'images/family',
        'images/graduation',
        'images/product'
    ],
    galleryCarouselFolder: 'images/gallery'
};

var sections = [
    {
        id: 'portraits', title: 'Portraits',
        banner: 'images/portraits/photo1.jpg', folder: 'images/portraits',
        albums: [
            { id: 'portraits-album-1', title: 'Album 1', cover: 'images/portraits/photo1.jpg', start: 1, end: 15 },
            { id: 'portraits-album-2', title: 'Album 2', cover: 'images/portraits/photo16.jpg', start: 16, end: 30 },
            { id: 'portraits-album-3', title: 'Album 3', cover: 'images/portraits/photo31.jpg', start: 31, end: 50 }
        ]
    },

    {
        id: 'sports', title: 'Sports',
        banner: 'images/sports/photo1.jpg', folder: 'images/sports',
        albums: [
            { id: 'sports-album-1', title: 'Album 1', cover: 'images/sports/photo1.jpg', start: 1, end: 15 },
            { id: 'sports-album-2', title: 'Album 2', cover: 'images/sports/photo16.jpg', start: 16, end: 30 },
            { id: 'sports-album-3', title: 'Album 3', cover: 'images/sports/photo31.jpg', start: 31, end: 50 }
        ]
    },

    {
        id: 'family', title: 'Family',
        banner: 'images/family/photo1.jpg', folder: 'images/family',
        albums: [
            { id: 'family-album-1', title: 'Album 1', cover: 'images/family/photo1.jpg', start: 1, end: 15 },
            { id: 'family-album-2', title: 'Album 2', cover: 'images/family/photo16.jpg', start: 16, end: 30 },
            { id: 'family-album-3', title: 'Album 3', cover: 'images/family/photo31.jpg', start: 31, end: 50 }
        ]
    },

    {
        id: 'graduation', title: 'Graduation',
        banner: 'images/graduation/photo1.jpg', folder: 'images/graduation',
        albums: [
            { id: 'graduation-album-1', title: 'Album 1', cover: 'images/graduation/photo1.jpg', start: 1, end: 15 },
            { id: 'graduation-album-2', title: 'Album 2', cover: 'images/graduation/photo16.jpg', start: 16, end: 30 },
            { id: 'graduation-album-3', title: 'Album 3', cover: 'images/graduation/photo31.jpg', start: 31, end: 50 }
        ]
    },

    {
        id: 'product', title: 'Product',
        banner: 'images/events/photo1.jpg', folder: 'images/product',
        albums: [
            { id: 'events-album-1', title: 'Album 1', cover: 'images/product/photo1.jpg', start: 1, end: 15 },
            { id: 'events-album-2', title: 'Album 2', cover: 'images/product/photo16.jpg', start: 16, end: 30 },
            { id: 'events-album-3', title: 'Album 3', cover: 'images/product/photo31.jpg', start: 31, end: 50 }
        ]
    }
];

var MAX_PHOTOS = 50;
