/* Photo Config — Generated by JBR Admin */

var homepageConfig = {
    heroImage:   'images/hero.jpg',
    aboutImage:  'images/about.jpg',
    portfolioCarouselFolders: [
        'images/portraits',
        'images/sports',
        'images/graduation',
        'images/family'
    ],
    galleryCarouselFolder: 'images/gallery'
};

var sections = [
    {
        id: 'portraits', title: 'Portraits',
        banner: 'images/portraits/photo2.jpg', bannerPosition: 'center 29%',
        folder: 'images/portraits',
        albums: [
            { id: 'portraits-album-1', title: 'Headshots', cover: 'images/portraits/photo1.jpg', coverPosition: 'center 27%', start: 1, end: 15 },
            { id: 'portraits-album-2', title: 'Greek Life', cover: 'images/portraits/photo16.jpg', coverPosition: 'center 50%', start: 16, end: 30 }
        ]
    },

    {
        id: 'sports', title: 'Sports',
        banner: 'images/sports/photo2.jpg', bannerPosition: 'center 38%',
        folder: 'images/sports',
        albums: [
            { id: 'sports-album-1', title: 'Hive Athletics', cover: 'images/sports/photo1.jpg', coverPosition: 'center 50%', start: 1, end: 15 }
        ]
    },

    {
        id: 'graduation', title: 'Graduation',
        banner: 'images/graduation/photo1.jpg', bannerPosition: 'center 5%',
        folder: 'images/graduation',
        albums: [
            { id: 'graduation-album-1', title: '', cover: 'images/graduation/photo1.jpg', coverPosition: 'center 50%', start: 1, end: 10 },
            { id: 'graduation-album-2', title: '', cover: 'images/graduation/photo16.jpg', coverPosition: 'center 66%', start: 11, end: 20 }
        ]
    },

    {
        id: 'family', title: 'Family',
        banner: 'images/family/photo2.jpg', bannerPosition: 'center 26%',
        folder: 'images/family',
        albums: [
            { id: 'family-album-1', title: '', cover: 'images/family/photo2.jpg', coverPosition: 'center 50%', start: 1, end: 15 }
        ]
    }
];

var MAX_PHOTOS = 50;
